AWSTemplateFormatVersion: 2010-09-09
Description: Serves a Jira Data Center cluster without a load balancer
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceProfile:
    Type: String
  Ami:
    Type: String
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 10.0.0.0/24
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: true
      CidrBlock: 10.0.0.0/24
      VpcId:
        Ref: VPC
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        -
          Key: Application
          Value:
            Ref: AWS::StackId
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  SubnetRouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: Subnet
  InternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: RouteTable
      GatewayId:
        Ref: InternetGateway
    DependsOn: AttachGateway
  jira1:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - Ref: SshSecurityGroup
        - Ref: RmiSecurityGroup
        - Ref: TomcatSecurityGroup
        - Ref: SubnetSecurityGroup
      InstanceType: c5.9xlarge
      SubnetId:
        Ref: Subnet
      KeyName:
        Ref: KeyName
      ImageId: !Ref Ami
      Tags:
        -
          Key: jpt-jira
          Value: true
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
  jira2:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - Ref: SshSecurityGroup
        - Ref: RmiSecurityGroup
        - Ref: TomcatSecurityGroup
        - Ref: SubnetSecurityGroup
      InstanceType: c5.9xlarge
      SubnetId:
        Ref: Subnet
      KeyName:
        Ref: KeyName
      ImageId: !Ref Ami
      Tags:
        -
          Key: jpt-jira
          Value: true
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
  SharedHome:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
      - Ref: SshSecurityGroup
      - Ref: SubnetSecurityGroup
      InstanceType: c5.9xlarge
      SubnetId:
        Ref: Subnet
      KeyName:
        Ref: KeyName
      ImageId: !Ref Ami
      Tags:
        -
          Key: jpt-shared-home
          Value: true
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
  Database:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c5.xlarge
      SubnetId:
        Ref: Subnet
      SecurityGroupIds:
        - Ref: SshSecurityGroup
        - Ref: MySqlSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId: !Ref Ami
      Tags:
        -
          Key: jpt-database
          Value: true
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enables SSH access
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  RmiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enables RMI access
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 40001
          ToPort: 40001
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 40011
          ToPort: 40011
          CidrIp: 0.0.0.0/0
  TomcatSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enables Tomcat HTTP access
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Security group for mount target
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0
  MySqlSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enables MySql access
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  SubnetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enable communication between nodes
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 10.0.0.0/24
