name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: 'Bump SemVer and release?'
        options:
          - 'No'
          - Patch
          - Minor
          - Major
        default: 'No'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Access AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew build
        timeout-minutes: 45
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: build
    if: github.event.inputs.release != null && github.event.inputs.release != 'No'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Access Maven
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
      - name: Release
        env:
          atlassian_private_username: ${{ steps.publish-token.outputs.artifactoryUsername }}
          atlassian_private_password: ${{ steps.publish-token.outputs.artifactoryApiKey }}
        run: |
          ./gradlew release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }} \
              -Prelease.versionIncrementer=increment${{ github.event.inputs.release }}
          ./gradlew publish
